### ISSUE TITLE
Allow user to add options to when creating application

### ISSUE THREAD

**Issue by ezkemboi** [kemboijs/kemboijs-cli#1]
This issue is big, but I will break down: 

In this stage: I need an algorithm/solution to allow users to add different parts/dependencies, e.g 
```bash
kemboijs-cli myapp fram=express db=postgres, sequelize test=mocha, chai, chai-http
```
Or 
```bash
kemboijs-cli myapp fram=express db=mongo,mongoose --no-tests
```

In the first example, I expect that the framework is set as express, then db to be postgres with help of sequelize ORM. Also, it will set tests based on the tools available. 

In the second example, it will not set any tests. 
When a user needs coverage reporting, then, he will have to define. 
```bash
kemboijs-cli myapp fram=express db=mongo,mongoose test=mocha,chai --coverage
```
Or, `nyc/any test runner coverage` availability in test argv will show directly that coverage is required.

**Comment by ronaldndirangu** [comment]
Great work @ezrqnkemboi however I think that for handling the initialization of an app using a generator that follows predefined steps such as the `yarn init` script would be better for this as it would avoid many of the edge cases that might arise from the above-said approach.

**Comment by ezrqnkemboi** [comment]
That is great feedback and will take consideration of that.

**Comment by ezrqnkemboi** [comment]
@ronaldndirangu I might develop the first instance using the first method, I had proposed. 
This is not to say the idea, will not be implemented, but I will leave the issue open until it is resolved. 
I will create just a replica of this issue and work on it. 

I am working on version 2, which will cover this issue and others that have arisen during the development process.

**Comment by ezkemboi** [comment]
@ronaldndirangu, can you have some time to check on pull request #40
