### ISSUE TITLE
create separate set up for development and testing database for Sequelize and Postgres

### ISSUE THREAD

**Issue by ezrqnkemboi** [kemboijs/kemboijs-cli#22]
- Currently, the setup sets up only one database connection. 
- Using config or .env files/instance, create a seperate database for testing and development. 

AS a bonus, we can add a production database.

**Comment by ezrqnkemboi** [comment]
Also, make sure to add `.env.example` file with the existing/necessary variables required in `.env`. 
Need more clarification Ping @ezrqnkemboi.

**Comment by Nicanor008** [comment]
Hey @ezrqnkemboi, assign me this issue, will work on it ASAP

**Comment by ezrqnkemboi** [comment]
Alright, @Nicanor008.
