### ISSUE TITLE
More updates on the readme and packages.json file

### ISSUE THREAD

**Issue by ezrqnkemboi** [kemboijs/kemboijs-cli#26]
- There are some grammatical issues that need to be checked and rectified. 
- Also, tell the user how to edit the database (const sequelize = new Sequelize('postgres://user:pass@example.com:5432/dbname'). Although it seems descriptive, there is need to add such description in Readme. Also, you can show the user how to make use of `.env` for such cases. 
- In packages.json, there are 2 and 3 instances that `nodejs` and `kemboijs` occurs in the keywords section. We only need one instance of each. 
- Also, add `how to contribute` to Readme file section.
- Any updates on the Readme, which is helpful to the user is also appreciated.

**Comment by Nicanor008** [comment]
Let me work on this issue

**Comment by ezrqnkemboi** [comment]
Assigned you the task @Nicanor008.
