### ISSUE TITLE
Add regex to check when user pass items that need to be in an array/objects

### ISSUE THREAD

**Issue by ezkemboi** [kemboijs/kemboijs-cli#7]
E.g. 
```bash
kemboijs-cli app fram=express db=postgres, sequelize test=chai,mocha
```
The seperation between postgres and sequelize will make sequelize not part of db but on its own. 
We need this done in the future. 
Though at the moment, user passes:
```bash
kemboijs-cli app fram=express db="postgres, sequelize" test=chai,mocha
```
Or, use it without whitespaces.

**Comment by ezrqnkemboi** [comment]
This will probably be invalid when #1 implementation changes.

**Comment by ezkemboi** [comment]
Asking questions, or using inquirer has solved this issue.
